import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "./ConvexClientProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({subsets:['latin']})

export default function RootLayout({ children }) {
  return (
    
    <ClerkProvider>
      <ConvexClientProvider>
    <html lang="en">
      <body
      className={outfit.className}
      // className="js-focus-visible"
      //             data-js-focus-visible=""
      >
        {children}
      </body>
    </html>
    </ConvexClientProvider>
    </ClerkProvider>
    
  );
}
